// ============================================
// Pothiq AI — App Constants
// ============================================

export const FARE_PER_KM = 2.45;
export const MIN_FARE = 10;
export const ADMIN_PIN_KEY = 'admin_pin_hash';
export const DEFAULT_PIN = '123456';
export const BCRYPT_ROUNDS = 10;
export const MAX_FAILED_ATTEMPTS = 5;
export const LOCK_DURATION_MS = 60 * 1000; // 60 seconds
export const AUTO_LOCK_MS = 5 * 60 * 1000; // 5 minutes
export const PAGE_SIZE = 20;
export const APP_VERSION = '1.0.0';
export const RECENT_SEARCHES_KEY = 'recent_searches';
export const SETTINGS_KEY = 'app_settings';
export const MAX_RECENT_SEARCHES = 5;

export const COLORS = {
  primary: '#1B5E20',
  primaryLight: '#4CAF50',
  primaryDark: '#0D3B0F',
  accent: '#FF6F00',
  accentLight: '#FFA040',
  background: '#F5F5F5',
  surface: '#FFFFFF',
  text: '#212121',
  textSecondary: '#757575',
  error: '#D32F2F',
  success: '#388E3C',
  warning: '#F57C00',
  divider: '#E0E0E0',
  // Dark mode
  darkBackground: '#121212',
  darkSurface: '#1E1E1E',
  darkText: '#FAFAFA',
  darkTextSecondary: '#B0B0B0',
  darkDivider: '#333333',
};

export const BENGALI_LABELS: Record<string, string> = {
  home: 'হোম',
  routes: 'রুটসমূহ',
  settings: 'সেটিংস',
  search: 'অনুসন্ধান',
  from: 'যাত্রা শুরু',
  to: 'গন্তব্য',
  searchRoutes: 'রুট খুঁজুন',
  recentSearches: 'সাম্প্রতিক অনুসন্ধান',
  noResults: 'কোনো রুট পাওয়া যায়নি',
  noResultsHint: 'অন্যান্য স্টপ দিয়ে চেষ্টা করুন',
  fixedFare: 'নির্ধারিত ভাড়া',
  distanceFare: 'দূরত্ব ভিত্তিক ভাড়া',
  distance: 'দূরত্ব',
  intermediateStops: 'মধ্যবর্তী স্টপ',
  allRoutes: 'সকল রুট',
  buses: 'বাস',
  stops: 'স্টপ',
  language: 'ভাষা',
  theme: 'থিম',
  darkMode: 'ডার্ক মোড',
  lightMode: 'লাইট মোড',
  about: 'সম্পর্কে',
  version: 'সংস্করণ',
  adminLogin: 'অ্যাডমিন লগইন',
  enterPin: 'পিন দিন',
  dashboard: 'ড্যাশবোর্ড',
  manageRoutes: 'রুট ব্যবস্থাপনা',
  manageBuses: 'বাস ব্যবস্থাপনা',
  manageStops: 'স্টপ ব্যবস্থাপনা',
  bulkImport: 'বাল্ক ইম্পোর্ট',
  backupRestore: 'ব্যাকআপ ও রিস্টোর',
  save: 'সংরক্ষণ',
  cancel: 'বাতিল',
  delete: 'মুছুন',
  edit: 'সম্পাদনা',
  add: 'যোগ করুন',
  swap: 'অদলবদল',
  fare: 'ভাড়া',
  bdt: '৳',
  km: 'কিমি',
  bus: 'বাস',
  route: 'রুট',
  stop: 'স্টপ',
  operator: 'অপারেটর',
  type: 'ধরন',
  area: 'এলাকা',
  active: 'সক্রিয়',
  inactive: 'নিষ্ক্রিয়',
  totalRoutes: 'মোট রুট',
  totalBuses: 'মোট বাস',
  totalStops: 'মোট স্টপ',
  logout: 'লগআউট',
  changePin: 'পিন পরিবর্তন',
  export: 'এক্সপোর্ট',
  import: 'ইম্পোর্ট',
  success: 'সফল',
  error: 'ত্রুটি',
  locked: 'লক করা হয়েছে',
  sos: 'এসওএস',
  tryAgainIn: 'আবার চেষ্টা করুন',
  seconds: 'সেকেন্ড',
  smartDhakaTransit: 'স্মার্ট ঢাকা ট্রানজিট',
  appName: 'পথিক এআই',
};

export const ENGLISH_LABELS: Record<string, string> = {
  home: 'Home',
  routes: 'Routes',
  settings: 'Settings',
  search: 'Search',
  from: 'From',
  to: 'To',
  searchRoutes: 'Search Routes',
  recentSearches: 'Recent Searches',
  noResults: 'No routes found',
  noResultsHint: 'Try different stops',
  fixedFare: 'Fixed Fare',
  distanceFare: 'Distance Fare',
  distance: 'Distance',
  intermediateStops: 'Intermediate Stops',
  allRoutes: 'All Routes',
  buses: 'Buses',
  stops: 'Stops',
  language: 'Language',
  theme: 'Theme',
  darkMode: 'Dark Mode',
  lightMode: 'Light Mode',
  about: 'About',
  version: 'Version',
  adminLogin: 'Admin Login',
  enterPin: 'Enter PIN',
  dashboard: 'Dashboard',
  manageRoutes: 'Manage Routes',
  manageBuses: 'Manage Buses',
  manageStops: 'Manage Stops',
  bulkImport: 'Bulk Import',
  backupRestore: 'Backup & Restore',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  add: 'Add',
  swap: 'Swap',
  fare: 'Fare',
  bdt: '৳',
  km: 'km',
  bus: 'Bus',
  route: 'Route',
  stop: 'Stop',
  operator: 'Operator',
  type: 'Type',
  area: 'Area',
  active: 'Active',
  inactive: 'Inactive',
  totalRoutes: 'Total Routes',
  totalBuses: 'Total Buses',
  totalStops: 'Total Stops',
  logout: 'Logout',
  changePin: 'Change PIN',
  export: 'Export',
  import: 'Import',
  success: 'Success',
  error: 'Error',
  locked: 'Locked',
  sos: 'SOS',
  tryAgainIn: 'Try again in',
  seconds: 'seconds',
  smartDhakaTransit: 'Smart Dhaka Transit',
  appName: 'Pothiq AI',
};
